### ISSUE TITLE
Could not load Tensorflow model

### ISSUE THREAD

**Issue by KeyiG** [seqcode/allo#1]
Hi,
I installed it through pip. The installation seems to be successful. But when I run it with testRunSE.sam. A error occurred: Could not load Tensorflow model. Tensorflow-2.17.0 is installed based on the message when installing allo. 
The command line I use is:
`allo testRunSE.sam -seq se -o testRUNSE_output`
And the output message is:

> Running Allo version 1.1
> 
> 
> Neural network mode on...
> Parsing finished!
> 
> Could not load Tensorflow model :( Allo was written with Tensorflow version 2.11

Thank you for your help in advance!

**Comment by anmorrissey** [comment]
Hello,
What version of Tensorflow are you using? Loading models in Tensorflow can be extremely finicky even with minor version changes.

**Comment by KeyiG** [comment]
Hi,
Thank you for the reply! I use Tensorflow-2.17.0 (when I installed Allo with pip, I saw in the output message that the version installed is 2.17.0). Do I need to use the exact same version 2.11?

**Comment by anmorrissey** [comment]
I have only tested loading the models up to version 2.16. It appears 2.17 came out very recently. I would downgrade your Tensorflow to 2.16 or earlier and it should work with this current version of Allo. If you're still having issues after the downgrade, let me know.

**Comment by KeyiG** [comment]
Hi,
Thank you very much for the help! 
I have tried to downgrade Tensorflow to 2.16.2 and 2.16.1, neither are working. Got the same error message. But when I downgraded to 2.12.0. it worked! But I got this warning in the output message: 

> DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
>   __import__('pkg_resources').require('bio-allo==1.1.1')

Do I need to worry?
Here is the output sam file using testRunSE.sam. Does it look correct?

> @PG collate
> 3	163	chr21	101	255	28M	=	153773227	49	CCTAATGTGGTGTATCCTGGGGAATTCT	EEEEEEEEEEEEEEEEEEEEEEAEEEEE	AS:i:-6	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:28	YS:i:0	YT:Z:CP	ZA:Z:4
> 4	163	chr2	103	255	28M	=	153773227	49	CCTAATGTGGTGTATCCTGGGGAATTCT	EEEEEEEEEEEEEEEEEEEEEEAEEEEE	AS:i:-7	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:28	YS:i:0	YT:Z:CP	ZA:Z:2
> 2	83	chr4	500	255	32M	=	153773210	-49	TGGGGAATTCTCCAGTTGCACTTGTGTGGTAA	EEEEEEEEEEEEEAEEEEEEEEAEAEEEEEEE	AS:i:10	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:32	YS:i:0	YT:Z:CP
> 1	177	chr21	103	1	28M	chr6	26379513	0	CCACCCCCCCCCCCCCCCCCCCCCCCCC	//A////A///EEEEEEEEEEEEEEEEE	AS:i:15	XS:i:0	XN:i:0	XM:i:0	XO:i:0	XG:i:0	NM:i:0	MD:Z:28	YT:Z:UP

Thank you very much for your time and help!

**Comment by anmorrissey** [comment]
Don't worry about the error message. I'll change some things on the next update to avoid it. Also, thank you for pointing out the version issues! I'll run some more tests to see which versions are the issue and update the dependencies with the next release.

**Comment by KeyiG** [comment]
Great, thank you :)

**Comment by xflicsu** [comment]
Is Allo suitable for HPC without GPU?

**Comment by anmorrissey** [comment]
> Is Allo suitable for HPC without GPU?

Yes. If you have issues loading the model with the CPU only version of TF, let us know.
