### ISSUE TITLE
Conda dependencies are broken?

### ISSUE THREAD

**Issue by pdexheimer** [seqcode/allo#3]
Hi -

I'm not sure whether I should file this here or in bioconda/bioconda-recipes, but I think that the updated tensorflow dependencies for pip added in daa6f6d didn't make it into bioconda.

I found this because both the [1.1.1](https://wave.seqera.io/view/builds/1fdeeb1ed2325f05_1) and [1.1.2](https://wave.seqera.io/view/builds/d82f741f4a63409a_1) containers at seqera fail with the following error:

```
Traceback (most recent call last):
  File "/opt/conda/bin/allo", line 31, in <module>
    import Allo
  File "/opt/conda/lib/python3.12/site-packages/Allo/__init__.py", line 1, in <module>
    from . import predictPeak
  File "/opt/conda/lib/python3.12/site-packages/Allo/predictPeak.py", line 9, in <module>
    from tensorflow.keras.models import load_model, Model
ModuleNotFoundError: No module named 'tensorflow.keras'
```

The build logs linked above show the versions of tensorflow that were used in the containers, it's 2.16.2 for 1.1.1 and 2.17.1 for 1.1.2.  A colleague of mine verified that a bare conda install failed with the same error when running `allo testRunPE.sam -seq pe`.  Building a [custom container](https://wave.seqera.io/view/builds/8bd1186fb6c1ef7a_1) where we forced tensorflow to 2.13.1 solved the issue

**Comment by anmorrissey** [comment]
It seems to be a consistent problem that even minor version changes will cause issues loading the models in Tensorflow. I'll be retraining networks using the newest version of Tensorflow within the next couple of days (same training dataset and parameters). That will at least allow Allo to be compatible with the newest version of tf. We are hoping to switch to PyTorch in the future as it seems less likely to have this issue. Thank you for working around this issue in the meantime and I appreciate you bringing it to our attention.

**Comment by anmorrissey** [comment]
The newest version of Allo includes models retrained using Tensorflow 2.17.
